### ISSUE TITLE
add a new component -- Regular Space

### ISSUE THREAD

**Issue by Zhouyuan-Chen** [wildmeshing/wildmeshing-toolkit#436]
I will add a new component called `regular_space`. This component is used to separate multiple inputs from each other.

#### Input:
* mesh
* tags recorded in each vertex or edge, tetrahedra (e.g. input tag)
* split tag (used for the new vertices or edges)
* dimension (used for the different situations, 0 for vertex, 1 for edge, and 2 for tetrahedra)
#### output:
* mesh
* tags recorded in each vertex or edge, tetrahedra

#### Todo List:
* [x] Component Skeleton
* [x] Face Split Operation
* [x] Face Split With Tag Operation
* [x] Edge Split With Tag Operation
* [x] Face Split Operation Test
* * seems the basic operation has a problem(split direction)
* [x] Edge Split With Tag Operation Test
* [x] Integrate Operations into the regular_space component (working on this)
* [x] regular_space component Test
* [x] a design diagram for other to read
* [x] JASON files layout (Check the JASON Array layout)

**Comment by Zhouyuan-Chen** [comment]
I just realized that there is no need to have a TagSplit or something similar operation, what we need is a Todo operation, that ensures the scheduler only does operations for those simplexes needed.

I modified my class structure, maybe I will rename the class later.

**Comment by Zhouyuan-Chen** [comment]
I almost finished the test part. this part can be used soon. But for now, my code still has much unrelated debug code. So I will commit the whole file later.

Before that, I think I will find someone to discuss the "bugs" for the ParaviewWriter...

I think there should be some potential problems in the IO class.
